version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '09:00'
    timezone: Asia/Tokyo