language: generic

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

sudo: false
dist: bionic
addons:
  apt:
    packages:
      - build-essential
      - fakeroot
      - git
      - libsecret-1-dev
      - libgconf2-4 # @TODO: Remove once Atom v1.39 is stable
