language: node_js
node_js:
  - 16

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

dist: bionic
addons:
  apt:
    packages:
      - build-essential
      - fakeroot
      - git
      - libsecret-1-dev
