name: Test

on: push

jobs:
  build-ui:
    needs: build-image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-2016, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        name: Start xvfb
        if: startsWith(matrix.os, 'ubuntu')
      - run: |
          echo ">>> Run integration test"
          yarn && yarn compile && yarn test
        name: Run Tests
        shell: bash
        env:
          DISPLAY: ':99.0'
