name: Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        name: Start xvfb
        if: startsWith(matrix.os, 'ubuntu')
      - run: |
          echo ">>> Run integration test"
          yarn && yarn compile && yarn test
        name: Run Tests
        shell: bash
        env:
          DISPLAY: ':99.0'
